### ISSUE TITLE
Update the README.md to make it clear how to log in to GitHub from IntelliJ IDEA

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/intro-to-git#25]
By default, the option to login using a token is selected in IntelliJ IDEA, and we should maybe mention that you would want to choose the password option at that point to help people not get stuck.

**Comment by kklamberty** [comment]
closed by commit 02004d071e3989f852cc8de6165ea367633e6cc1

**Comment by floogulinc** [comment]
Actually students should probably use token login for git in intelij

**Comment by joethe** [comment]
I agree with @floogulinc here. You can just press the button to generate a token right in the IntelliJ dialog, and it would be cool to show off the Personal Access Token management bits inside GitHub, and explain how useful it is to be able to revoke access for a token.

A fun example is that if you're using Microsoft Azure DevOps (formerly VSTS) or many of the other MS tools, you are actively discouraged from using any kind of authentication other than purpose-generated tokens with specific expiration dates and access restrictions - so much so that setting it up to use password authentication is, in my opinion, designed to be frustrating.

**Comment by floogulinc** [comment]
@kklamberty @NicMcPhee
