### ISSUE TITLE
Update README.md to choose one approach for git usage for each part

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/intro-to-git#34]
The current version of the README.md instructions explains how to use git from the command line AND how to use GitHub from within IntelliJ for almost every aspect of the lab. This made it challenging to help people since we didn't know their trajectory. We might consider making them use a command line and plain editor for the first part (pronouns and github username part) and IntelliJ IDEA for the second part. This might also be a good place to include a couple hints about VIM.

**Comment by NicMcPhee** [comment]
I like this, and I like that particular split. They don't benefit much from all the "fancies" that IntelliJ provides when they're just doing the names/pronouns part, so doing it all on the command line seems good. Then they get IntelliJ when they get to coding, where IntelliJ will do them the most good.

We might also have them delete the copy they checked out via the command line, and then checkout it all out from scratch in IntelliJ for the second half?

**Comment by joethe** [comment]
Just as a fun aside, even sitting at a desk writing commits for 10 hours a day I don't really find myself benefiting from the IntelliJ fancies all that much. IntelliJ's git integration is good, but I think contains a lot of weird little quirks which are non-obvious if you don't have a solid grasp of how git works prior to bumping into them... I think the only IntelliJ fancy I actually use on a regular basis is the merge/diff tools for resolving conflicts.

**Comment by kklamberty** [comment]
I didn't do this for fall 2019, and I wish I would have. I think it should be a high priority for us to update the lab to include a definite split between command line and built in tools. We are planning to use GitKraken in the Spring 2020 offering, so I think that this might be even more important to consider. We need to know how best to help the students and we want to be clear that this is at least partly about exploring different options for using git (and ending with whatever version we plan to use for the rest of the course, in my opinion). If we use Visual Studio Code we will also need to update to include that here.

**Comment by NicMcPhee** [comment]
I like your idea of solely using command line in the first lab, and then Gitkraken/VSCode in the second lab. It would almost certainly make things cleaner & clearer.

If we do this, then one thing we'll have to document/explain in the first lab is how merge conflicts are represented in the file (the whole `<<<<`, `====`, `>>>>` thing) and how to deal with that:

- Editing the file to remove the conflict parts
- Use `git add` to tell `git` you're done resolving the conflict
- Commit and push. 

It would be worth searching for a nice write-up of that that is already out there on the Internet.

Then we should probably do something about merge conflicts in Gitkraken/VS Code. I actually find VS Code's handling of conflicts to be the best of any IDE that I've used, even though it's general `git` integration is nothing to write home about. Just yesterday in Practicum I worked with a pair of students that were having a merge conflict problem, and we did _everything_ on the command line except for actually resolving the merge conflict, which we did in VS Code, and it worked really nicely.

**Comment by floogulinc** [comment]
GitKraken also provides [very nice handling of merge conflicts](https://support.gitkraken.com/working-with-repositories/branching-and-merging/#merge-conflict-editor). It shows you the two versions of the file side-by-side and has you select which parts of the file to keep in the final (shown below the two panes). 

![](https://support.gitkraken.com/img/documentation/repositories/local_repository/merge-tool-toggle.gif)

It should be noted that this merge conflict feature is only for the paid version, but students get that for free with the GitHub Student Pack (and we should have them sign up for it before using GitKraken).

GitKraken also has [first-class support for GitHub pull requests](https://support.gitkraken.com/working-with-repositories/pull-requests/). This means you can create and checkout pull requests right from GitKraken, and when there is a potential merge-conflict it will warn you. 

It might be beneficial to to choose to use *just* GitKraken or VSCode for Git stuff instead of switching between them.

**Comment by NicMcPhee** [comment]
This was closed as part of the big PR #35.
