### ISSUE TITLE
Switch default branch to `main`

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/intro-to-git#54]
As per ["Replacing master with main in GitHub"](https://dev.to/afrodevgirl/replacing-master-with-main-in-github-2fjf), which has instructions on how to do it.

* [ ] ❗ Update the branch reference in the BetterGitHub badge. Changing the default branch may also "break" things on LGTM so that will need to be checked as well.
* [x] ❗ Update the branch protections so `main` is now protected.
* [x]  ❗ Update any open pull requests to target `main` instead of `master`.

**Comment by floogulinc** [comment]
According to the [official docs](https://github.com/github/renaming) from GitHub:

> **If you haven’t renamed your default branch yet, consider waiting until [later this year](#later-this-year). We’re investing in tools to make renaming the default branch of an existing repository a seamless experience for both maintainers and contributors.**

<blockquote>

For existing repositories, renaming the default branch today causes a set of challenges:

- Open pull requests need to be retargeted to the new branch
- Draft releases need to be retargeted to the new branch
- Branch protection policies need to be transferred to the new branch

By the end of the year, we'll make it seamless for existing repositories to rename their default branch. When you rename the branch, we’ll retarget your open PRs and draft releases, move your branch protection policies, and more - all automatically. And, we’re also looking into redirecting users who `git fetch` or `git clone` the old branch name to the new branch name (with a warning and instructions to update their local clone), so it’s easy for your contributors to move.

</blockquote>


So I think we should hold off on this until then, it's not as simple as the linked article describes because of things like open PRs, bot configurations, GH Actions, etc.

**Comment by NicMcPhee** [comment]
It looks like their "official" tooling is supposed to roll out "sometime in January", I need to be ready for classes in a week, so I'm going to start doing this "by hand", especially on the early labs like this one where there aren't a lot of pull requests to "break".
