### ISSUE TITLE
Clarify what repo to clone

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/intro-to-git#7]
The current writeup tells how to clone the repo and has an example of what the url might look like... but some groups copied that example rather than following the instructions of *how* to do this.

**Comment by danfrz** [comment]
I think this would need to happen before each intro-to-git lab, because making the example repo the actual repo for this semester would tie it to one semesters' fork of the intro-to-git repo. Then when the next semester comes around confusion may insue.

I suppose we could make the example repo really look like an example repo, something like this:
```
https://github.com/GROUP-OR-USER/repository-name.git
```
